"COMMAND:\n  - name: Second Order System\n    key: SECOND_ORDER_SYSTEM\n    type:\
  \ SIMULATION\n    parameters:\n      d1: \n        type: float\n        default:\
  \ 250\n      d2: \n        type: float\n        default: 100"
