"COMMAND:\n  - name: PID\n    key: PID\n    type: SIGNAL_PROCESSING\n    parameters:\n\
  \      Kp: \n        type: float\n        default: 5\n      Ki: \n        type:\
  \ float\n        default: 0.0143\n      Kd: \n        type: float\n        default:\
  \ 356.25"
