"COMMAND:\n  - name: Detrend\n    key: DETREND\n    type: SCIPY_SIGNAL\n    parameters:\
  \ \n      axis: \n        type: int\n        default: -1 \n      type: \n      \
  \  type: string\n        default: linear \n      bp: \n        type: int\n     \
  \   default: 0 \n      overwrite_data: \n        type: boolean\n        default:\
  \ False"
