"COMMAND:\n  - name: Low-pass FIR Filter\n    key: FIR\n    type: SIGNAL_PROCESSING\n\
  \    parameters:\n      sample_rate:\n        type: float\n        default: 100\n\
  \      transition_width:\n        type: float\n        default: 5.0\n      stop_band_attenuation:\n\
  \        type: float\n        default: 60\n      cutoff_freq:\n        type: float\n\
  \        default: 10.0"
