cutoff_high:
  default: 15.0
  type: float
cutoff_low:
  default: 10.0
  type: float
filter_type:
  default: lowpass
  options:
  - lowpass
  - highpass
  - bandpass
  - bandstop
  type: select
sample_rate:
  default: 100
  type: float
taps:
  default: 200
  type: int
window:
  default: hann
  options:
  - boxcar
  - triang
  - blackman
  - hamming
  - hann
  - bartlett
  - flattop
  - parzen
  - bohman
  - blackmanharris
  - nuttall
  - barthann
  - cosine
  - exponential
  - tukey
  - taylor
  - lanczos
  type: select
