"COMMAND:\n- name: SCATTER\n  key: SCATTER\n  type: PLOTLY_VISOR\n  inputs:\n  - name:\
  \ default\n    id: default\n    type: OrderedPair|DataFrame|Matrix\n  outputs:\n\
  \  - name: default\n    id: default\n    type: Plotly\n"
