window_type:
  type: select
  options:
    - none
    - boxcar
    - triang
    - blackman
    - hamming
    - hann
    - bartlett
    - flattop
    - parzen
    - bohman
    - blackmanharris
    - nuttall
    - barthann
    - cosine
    - exponential
    - tukey
    - taylor
    - lanczos
  default: none
display:
  type: boolean
  default: true
real_signal:
  type: boolean
  default: false
sample_rate:
  type: int
  default: 1