"COMMAND:\n  - name: Welch\n    key: WELCH\n    type: SCIPY_SIGNAL\n    parameters:\
  \ \n      fs: \n        type: float\n        default: 1.0 \n      window: \n   \
  \     type: string\n        default: hann \n      nperseg: \n        type: int\n\
  \        default:  \n      noverlap: \n        type: int\n        default:  \n \
  \     nfft: \n        type: int\n        default:  \n      detrend: \n        type:\
  \ string\n        default: constant \n      return_onesided: \n        type: boolean\n\
  \        default: True \n      scaling: \n        type: string\n        default:\
  \ density \n      axis: \n        type: int\n        default: -1 \n      average:\
  \ \n        type: string\n        default: mean"
