"COMMAND:\n  - name: Prophet Plot\n    key: PROPHET_PLOT\n    type: PLOTLY_VISOR\n\
  \    parameters:\n      periods:\n        type: int\n        default: 365\n    pip_dependencies:\n\
  \      - name: prophet\n        v: \"1.1.4\""
