"COMMAND:\n  - name: Mode\n    key: MODE\n    type: SCIPY_STATS\n    parameters: \n\
  \      axis: \n        type: int\n        default: 0 \n      nan_policy: \n    \
  \    type: string\n        default: propagate \n      keepdims: \n        type:\
  \ boolean\n        default:"
