"COMMAND:\n  - name: Composite plot \n    key: COMPOSITE\n    type: PLOTLY_VISOR\n\
  \    inputs:\n      - name: primary_trace\n        id: primary_trace\n        type:\
  \ source\n      - name: secondary_trace\n        id: secondary_trace\n        type:\
  \ source\n    parameters:\n      first_figure:\n        type: select\n        options:\n\
  \          - bar\n          - line\n          - histogram\n          - scatter\n\
  \        default: scatter\n      second_figure:\n        type: select\n        options:\n\
  \          - bar\n          - line\n          - histogram\n          - scatter\n\
  \        default: scatter"
