"COMMAND:\n  - name: Hilbert\n    key: HILBERT\n    type: SCIPY_SIGNAL\n    parameters:\
  \ \n      N: \n        type: int\n        default:  \n      axis: \n        type:\
  \ int\n        default: -1"
