"COMMAND:\n  - name: Gstd\n    key: GSTD\n    type: SCIPY_STATS\n    parameters: \n\
  \      axis: \n        type: int\n        default: 0 \n      ddof: \n        type:\
  \ int\n        default: 1"
