"COMMAND:\n  - name: Sine\n    key: SINE\n    type: SIMULATION\n    parameters:\n\
  \      frequency:\n        type: float\n        default: 1\n      offset:\n    \
  \    type: float\n        default: 0\n      amplitude:\n        type: float\n  \
  \      default: 1\n      phase:\n        type: float\n        default: 0.0\n   \
  \   waveform:\n        type: select\n        options:\n          - sine\n      \
  \    - square\n          - triangle\n          - sawtooth\n        default: sine"
