"COMMAND:\n- name: SINE\n  key: SINE\n  type: SIMULATION\n  inputs:\n  - name: default\n\
  \    id: default\n    type: OrderedPair\n  parameters:\n    amplitude:\n      type:\
  \ float\n      default: 1\n    frequency:\n      type: float\n      default: 1\n\
  \    offset:\n      type: float\n      default: 0\n    phase:\n      type: float\n\
  \      default: 0\n    waveform:\n      type: select\n      options:\n      - sine\n\
  \      - square\n      - triangle\n      - sawtooth\n      default: sine\n  outputs:\n\
  \  - name: default\n    id: default\n    type: OrderedPair\n"
