"COMMAND:\n  - name: Pinv\n    key: PINV\n    type: NUMPY_LINALG\n    parameters:\
  \ \n      rcond: \n        type: float\n        default: 1e-15 \n      hermitian:\
  \ \n        type: boolean\n        default: False"
