"COMMAND:\n  - name: KEITHLEY2400\n    key: KEITHLEY2400\n    type: KEITHLEY\n   \
  \ parameters:\n      comport:\n        type: string\n        default: '/dev/ttyUSB0'\n\
  \      baudrate:\n        type: float\n        default: 9600\n    pip_dependencies:\n\
  \      - name: pyserial\n        v: \"3.5\""
