"COMMAND:\n  - name: Argrelmax\n    key: ARGRELMAX\n    type: SCIPY_SIGNAL\n    parameters:\
  \ \n      axis: \n        type: int\n        default: 0 \n      order: \n      \
  \  type: int\n        default: 1 \n      mode: \n        type: string\n        default:\
  \ clip"
