"COMMAND:\n  - name: Describe\n    key: DESCRIBE\n    type: SCIPY_STATS\n    parameters:\
  \ \n      axis: \n        type: int\n        default: 0 \n      ddof: \n       \
  \ type: int\n        default: 1 \n      bias: \n        type: boolean\n        default:\
  \ True \n      nan_policy: \n        type: string\n        default: propagate"
