"COMMAND:\n  - name: Trim1\n    key: TRIM1\n    type: SCIPY_STATS\n    parameters:\
  \ \n      proportiontocut: \n        type: float\n        default:  \n      tail:\
  \ \n        type: string\n        default: right \n      axis: \n        type: int\n\
  \        default: 0"
