"COMMAND:\n  - name: PHIDGET22\n    key: PHIDGET22\n    type: PHIDGET\n    parameters:\n\
  \      n_sensors:\n        type: int\n        default: 3\n      calibration1 :\n\
  \        type: float\n        default: 0.015\n      calibration2:\n        type:\
  \ float\n        default: 0.06\n    pip_dependencies:\n      - name: Phidget22"
