"COMMAND:\n  - name: Sigmaclip\n    key: SIGMACLIP\n    type: SCIPY_STATS\n    parameters:\
  \ \n      low: \n        type: float\n        default: 4.0 \n      high: \n    \
  \    type: float\n        default: 4.0"
