"COMMAND:\n  - name: Tmin\n    key: TMIN\n    type: SCIPY_STATS\n    parameters: \n\
  \      lowerlimit: \n        type: float\n        default:  \n      axis: \n   \
  \     type: int\n        default: 0 \n      inclusive: \n        type: boolean\n\
  \        default: True \n      nan_policy: \n        type: string\n        default:\
  \ propagate"
