"COMMAND:\n  - name: Matrix\n    key: MATRIX\n    type: SIMULATION\n    ui_component_id:\
  \ default\n    parameters:\n      row:\n        type: int\n        default: 2\n\
  \      column:\n        type: int\n        default: 2"
