"COMMAND:\n  - name: Czt\n    key: CZT\n    type: SCIPY_SIGNAL\n    parameters: \n\
  \      m: \n        type: int\n        default:  \n      w: \n        type: complex\n\
  \        default:  \n      axis: \n        type: int\n        default: -1"
