"COMMAND:\n  - name: Linspace\n    key: LINSPACE\n    type: SIMULATION\n    ui_component_id:\
  \ default\n    parameters:\n      start:\n        type: float\n        default:\
  \ 10\n      end:\n        type: float\n        default: 0\n      step:\n       \
  \ type: int\n        default: 1000"
