amplitude:
  default: 1
  type: float
frequency:
  default: 1
  type: float
offset:
  default: 0
  type: float
phase:
  default: 0.0
  type: float
waveform:
  default: sine
  options:
  - sine
  - square
  - triangle
  - sawtooth
  type: select
