"COMMAND:\n  - name: BIG_NUMBER\n    key: BIG_NUMBER\n    type: PLOTLY_VISOR\n   \
  \ parameters:\n      suffix:\n        type: string\n        default: \"\"\n    \
  \  prefix:\n        type: string\n        default: \"\"\n      relative_delta:\n\
  \        type: select\n        options:\n          - \"true\"\n          - \"false\"\
  \n        default: \"true\"\n      title:\n        type: string\n        default:\
  \ \"\""
