"COMMAND:\n  - name: Kurtosis\n    key: KURTOSIS\n    type: SCIPY_STATS\n    parameters:\
  \ \n      axis: \n        type: int\n        default: 0 \n      fisher: \n     \
  \   type: boolean\n        default: True \n      bias: \n        type: boolean\n\
  \        default: True \n      nan_policy: \n        type: string\n        default:\
  \ propagate \n      keepdims: \n        type: boolean\n        default: False"
