"COMMAND:\n  - name: SERIAL_SINGLE_MEASUREMENT\n    key: SERIAL_SINGLE_MEASUREMENT\n\
  \    type: SERIAL\n    parameters:\n      comport:\n        type: string\n     \
  \   default: \"/dev/ttyUSB0\"\n      baudrate:\n        type: float\n        default:\
  \ 9600\n    pip_dependencies:\n      - name: pyserial\n        v: \"3.5\""
