"COMMAND:\n  - name: Skewtest\n    key: SKEWTEST\n    type: SCIPY_STATS\n    parameters:\
  \ \n      axis: \n        type: int\n        default: 0 \n      nan_policy: \n \
  \       type: string\n        default: propagate \n      alternative: \n       \
  \ type: string\n        default: two-sided"
