"COMMAND:\n  - name: Variation\n    key: VARIATION\n    type: SCIPY_STATS\n    parameters:\
  \ \n      axis: \n        type: int\n        default: 0 \n      nan_policy: \n \
  \       type: string\n        default: propagate \n      ddof: \n        type: int\n\
  \        default: 0 \n      keepdims: \n        type: boolean\n        default:\
  \ False"
