"COMMAND:\n  - name: Zscore\n    key: ZSCORE\n    type: SCIPY_STATS\n    parameters:\
  \ \n      axis: \n        type: int\n        default: 0 \n      ddof: \n       \
  \ type: int\n        default: 0 \n      nan_policy: \n        type: string\n   \
  \     default: propagate"
