"COMMAND:\n  - name: Stft\n    key: STFT\n    type: SCIPY_SIGNAL\n    parameters:\
  \ \n      fs: \n        type: float\n        default: 1.0 \n      window: \n   \
  \     type: string\n        default: hann \n      nperseg: \n        type: int\n\
  \        default: 256 \n      noverlap: \n        type: int\n        default:  \n\
  \      nfft: \n        type: int\n        default:  \n      detrend: \n        type:\
  \ boolean\n        default: False \n      return_onesided: \n        type: boolean\n\
  \        default: True \n      boundary: \n        type: string\n        default:\
  \ zeros \n      padded: \n        type: boolean\n        default: True \n      axis:\
  \ \n        type: int\n        default: -1 \n      scaling: \n        type: string\n\
  \        default: spectrum"
