name: Algolia Index

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight (UTC time)
  workflow_dispatch:

jobs:
  cron_job:
    runs-on: ubuntu-latest

    env:
      APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
      API_KEY: ${{ secrets.ALGOLIA_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run cron job
        run: docker run -it -e "CONFIG=$(cat ./config.json | jq -r tostring)" algolia/docsearch-scraper
