name: 'Build Docusaurus'
on:
  pull_request:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-docusaurus:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          node-version: '16'        
      # Node is required for npm
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      # Install and build Docusaurus website
      - name: Build Docusaurus website
        run: |
          npm install 
          npm run build