"COMMAND:\n  - name: Subtract\n    key: SUBTRACT\n    type: ARITHMETIC\n    inputs:\n\
  \      - name: x\n        id: sub_x\n        type: target\n      - name: y\n   \
  \     id: sub_y\n        type: target"
